### ISSUE TITLE
Remove bracket-int notation in Subsetting&Filtering

### ISSUE THREAD

**Issue by eswan18** [uc-python/intro-python-datasci#10]
In the subsetting and filtering notebook, we show a way of selecting rows by using bracket notation on the dataframe directly:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/3449508/57158894-91d87880-6db2-11e9-830c-f5a89d51eada.png">

However, it is not only *misleading* (as pointed out above), but it is actually ambiguous – in certain cases (many, I think), it will select columns and not rows.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/3449508/57158858-73727d00-6db2-11e9-8811-44ae44715bf4.png">

Note that in this case, passing an integer selected a column (not a row).
For clarity and simplicity, I believe we should not even introduce this syntax as an option.

**Comment by markroepke** [comment]
Good catch. I'll remove it.

**Comment by eswan18** [comment]
Looks good
