### ISSUE TITLE
Manipulating Columns Review

### ISSUE THREAD

**Issue by markroepke** [uc-python/intro-python-datasci#11]
Looks good, @eswan18. I only have three comments:

1. Should we include the DataFrame/Series relationship in Applied Review? This seems key to the section. There are examples of this in Subsetting & Filtering.
2. Do we want to talk about using `DataFrame.map({})` for `CASE WHEN`-like behavior? Or at least provide an example? This is a common task and it could be beneficial to include an example.
3. We still need to add exercises.

**Comment by eswan18** [comment]
I think I've addressed all these in the 3 commits above. Can you review and close this issue if you're happy with the changes?

**Comment by markroepke** [comment]
These look good to me. Adjustments to 2 and 3 look great. The only remaining concern is related to 1. I see you added some Applied Review, but nothing related to the DataFrame/Series relationship -- this could be key since a column is effectively a Series and this section is about manipulating columns.

My comment above was unclear and misleading. When I mentioned that there were examples of this in the Subsetting & Filtering section, I should've specified that the example was NOT in the Applied Review.

Here is what I'm talking about:

<img width="761" alt="Screen Shot 2019-05-08 at 7 04 03 AM" src="https://user-images.githubusercontent.com/26677807/57371006-9fe61a80-715f-11e9-8516-009dbe6773b9.png">

Including a bullet in Applied Review on this material (which is prior to Manipulating Columns) is my primary concern. Sorry for not being clear with 1.

**Comment by eswan18** [comment]
I think I understand what you mean. Check the most recent commit and see if it's what you were thinking.

**Comment by markroepke** [comment]
Perfect. Thanks.
