### ISSUE TITLE
Packages/Modules/Methods/Functions Review

### ISSUE THREAD

**Issue by markroepke** [uc-python/intro-python-datasci#12]
Converting conversation from 8ad221e to issue for tracking.

I agree this section looks a little long, but we could shorten relatively easily. I don't think we need to include anything about slicing here as it's in the subsetting notebook -- it seems to be a better fit there and it is a good way to revisit the Index.

The only other major suggestion I have is a visual describing the relationships between packages/modules/objects/functions/methods/attributes. I think that could serve as a great reference for students as they move forward. Thoughts?

**Comment by eswan18** [comment]
Will definitely remove slicing.
I'll have to think more about the visual, but I agree it would be a helpful addition.

**Comment by eswan18** [comment]
Settled on a visual:
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/3449508/57499774-e26a3d00-72ae-11e9-96ab-d7a9dc5fe5a4.png">

**Comment by markroepke** [comment]
I love it. Thanks.
