### ISSUE TITLE
Now-inaccurate description of course resource layout

### ISSUE THREAD

**Issue by eswan18** [uc-python/intro-python-datasci#17]
Our current direction is for our notebooks to *be* our slides -- we aren't using separate files for slides. That makes this bit of the Python & Jupyter Overview notebook inaccurate.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/3449508/57495862-0bce9d00-729e-11e9-839a-5bf867e1dfff.png">

**Comment by markroepke** [comment]
Do we want to move everything to a "notebooks" or "slides" subdirectory? They're currently in notebooks but designed to be viewed as slides.

**Comment by eswan18** [comment]
I don't feel strongly at all, whatever you think is best.

I would lean "notebooks" since that's what they really are, and I don't think it'll cause much confusion. But it really doesn't matter.

**Comment by markroepke** [comment]
This is addressed in the above commit, and the issue should close when the commit is merged to master.
