### ISSUE TITLE
There is no space for students to complete exercises

### ISSUE THREAD

**Issue by markroepke** [uc-python/intro-python-datasci#19]
We currently do not have space for students to complete Your Turn exercises. We have a few options here:

1. Create an "Exercise" notebook with all of the Your Turn exercises where students can get used to working in an actual notebook environment
2. Add open cells following exercises within the slides for students to keep slide environment open
3. Create corresponding worksheet notebook versions of slides notebooks to combine the benefits of 1 and 2

We've discussed taking option 2 for the initial training, but option 3 may be best in the long run. We'll see what kind of feedback we get with option 2 in this initial training.

Regardless, all notebooks must have the exercise spaces built in.

**Comment by eswan18** [comment]
With how easy it is to switch from slides to notebooks, I think we should just have them switch out of slides and create a new cell in notebooks. I would not be at all surprised if some preferred to follow along in notebook form anyway.

Don't think this is a pressing issue at all, but you can update it if you want.

**Comment by markroepke** [comment]
I think that's a good strategy for this training. We'll have to see how people like it.

I can see how students would learn by exiting the slideshow (if they're in it), creating a new cell, and doing the exercise, but I could also see this as an inconsequential distraction when their focus should be on other material (increasing extrinsic cognitive load).

I'll create a kanban board for the second iteration of the training for us to revisit this.

**Comment by markroepke** [comment]
This doesn't appear to be an issue during class. Closing issue, won't fix.
