### ISSUE TITLE
Content runs off slides in a few notebooks

### ISSUE THREAD

**Issue by markroepke** [uc-python/intro-python-datasci#20]
The content runs off of a few slides in notebooks:

- [x] Fundamentals
- [x] PMMF
- [x] Manipulating Columns
- [x] Visualizing Data

This is an easy fix, but I just want to call attention to it. I'm good with fixing issues in the notebooks I'm presenting which we'll decide on tonight.

**Comment by eswan18** [comment]
Hmm what do all these notebooks have in common? No idea

**Comment by markroepke** [comment]
Haha, I wasn't going to leave that in the ink of the internet, but yes. Not
a big deal at all.

**Comment by eswan18** [comment]
This should close when merged to master.
