### ISSUE TITLE
Add building block examples for agg in Subsetting

### ISSUE THREAD

**Issue by markroepke** [uc-python/intro-python-datasci#31]
We kinda lost people on the agg() method during the first iteration. It would likely be helpful to introduce agg() with simpler examples that are more similar in result to the summary methods.

**Comment by eswan18** [comment]
I think in recent iterations we've had no trouble covering `agg`, and if I recall correctly, we did make some simplifications to this section a while back. Closing this, but @bradleyboehmke feel free to reopen if you disagree.
