### ISSUE TITLE
Add closing slides and information

### ISSUE THREAD

**Issue by markroepke** [uc-python/intro-python-datasci#38]
This would be good to get in the repo.

- Thanks for coming
- Next course date
- How to learn more
  - Podcasts
  - Books
  - Blogs

Anything else? I know you made a quick version of this last time.

**Comment by eswan18** [comment]
We can just copy the 10-Closing.ipynb file from the [intermediate training](https://github.com/uc-python/intermediate-python-datasci).

**Comment by eswan18** [comment]
Closed in 1e3166
