### ISSUE TITLE
More detailed explanation of saving index

### ISSUE THREAD

**Issue by eswan18** [uc-python/intro-python-datasci#6]
*In Exporting Data*: Could you add a little more explanation to what is happening here (indexes being saved automatically, even though they aren't actually a column in the original data)?

![image](https://user-images.githubusercontent.com/3449508/56095547-19198700-5eac-11e9-93fc-30787b76f4ef.png)

**Comment by markroepke** [comment]
Sure, I can add something about the index being saved by default. Though I intentionally avoided a verbose explanation for two reasons:

1. The DataFrame index should be explained in Fundamentals or Packages, Modules, Methods, Functions given that we agreed the basics of the DataFrame class would be covered within these sections.
2. These are visual aids and I anticipate verbal clarifications of what's happening here. I'm of the opinion that these aren't necessarily supposed contain all the details.

With that being said, I'll add a brief comment about the index not being part of the original data but being saved as a column by default. It's always good to review the concept of the index, anyways.

**Comment by eswan18** [comment]
Makes sense. I would have breezed over indexes, since they're pretty complicated, but I'll make sure to add at least a little bit of content on them so students will be familiar when we encounter this.

**Comment by markroepke** [comment]
I made the discussed additions, but also want to point out there was an HTML-created discussion question already there (not rendering it GitHub) that I forgot about earlier -- hopefully these address the concern here.

For reference, here's what it looks like fully rendered:

<img width="1065" alt="Screen Shot 2019-04-14 at 4 20 46 PM" src="https://user-images.githubusercontent.com/26677807/56098763-f39f7400-5ed1-11e9-959a-8174856b82a3.png">

Please close if you feel good about this.
