### ISSUE TITLE
Row/column/cell highlighting doesn't render in GitHub

### ISSUE THREAD

**Issue by markroepke** [uc-python/intro-python-datasci#7]
The row/column/cell highlighting in the subsetting_and_filtering.ipynb is not rendering in the notebooks on GitHub. We need to determine whether or not it will appear in slides and how to hide the input code.

There should be extensions for this, I would think.

**Comment by eswan18** [comment]
Have never even seen this feature before (`df.style....`). Very cool and would be nice to get it working, but it's not the end of the world if we can't.

**Comment by markroepke** [comment]
Yeah, we could always copy/paste the image from elsewhere to highlight certain rows but it would be great to get it code-based.

I'm going to try to finish the content over the next few days then I'll look into this.

**Comment by markroepke** [comment]
I don't believe this is an issue. The highlighting renders in slides, but we still need to figure out how to hide the input code. Opening #8 to be more specific.
